exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

highlighter: pygments
url: http://lo5an.com
permalink:  pretty
permalink: /:year/:title/

# kebase.io files
include: [".well-known"]


# Build settings
markdown: kramdown

